config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/blog')
  get '/blog', to: 'posts#index', as: 'posts'

  resources :posts, only: :index do
    resources :comments, only: :create
  end

  resources :questions, only: [:index, :create] do
    resources :question_comments, only: :create
  end

  namespace :admin do
    root 'posts#index'
    resources :posts, except: :show do
      resources :comments, only: [:index, :destroy]
    end
    
    resources :questions, only: [:index, :destroy, :edit, :update] do
      resources :question_comments, only: [:index, :create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to admin_posts_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# comments controller
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to posts_path
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container pb-2 mt-4 mb-2 border-bottom">
  <h1>HogsBurgerBlog admin</h1>
</div>
<div class="container">
  <h2>Comments for post <%= link_to @post.title, edit_admin_post_path(@post) %></h2>
  <table class="table" />
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th></th>
    </tr>

    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td>
          <%= link_to 'X', admin_post_comment_path(@post, comment), class: "btn btn-danger btn-xs",
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
      </td>
      </tr>
    <% end %>
  </table>
</div>