config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/blog')
  get '/blog', to: 'posts#index', as: 'posts'

  resources :posts, only: :index do
    resources :comments, only: :create
  end

  resources :questions, only: [:index, :create] do
    resources :question_comments, only: :create
  end

  namespace :admin do
    root 'posts#index'
    resources :posts, except: :show do
      resources :comments, only: [:index, :destroy]
    end
    
    resources :questions, only: [:index, :destroy, :edit, :update] do
      resources :question_comments, only: [:index, :create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { minimum: 10 }
  validates :rating, presence: true
  validates :image, presence: true
  has_one_attached :image

  def self.search(search)
    if search and search != ""
      Post.where('text like ? or title like ?', "%#{search}%", "%#{search}%")
    else
      Post.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  include HttpAuthConcern

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image, :rating)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :sort_column, :sort_direction, :search

  def index
    @posts = Post.search(params[:search])
    if sort_direction != ''
      @posts = @posts.order("#{sort_column} #{sort_direction}")
    else
      @posts = @posts.order("updated_at desc")
    end
    @posts
  end

  def post_params
    params.require(:post).permit(:search)
  end

  private

  def sortable_columns
    %w[rating updated_at]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : 'rating'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : ''
  end

  def search
    params[:search]
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_rating(post)
    post.rating.times.collect do
      content_tag(:div, class: "col-1 pr-0 pl-0 burger-icon") do
        burger()
      end
    end.join.html_safe
  end

  def burger
    image_tag("burger.png", class: "img-fluid")
  end

  def burger_colour
    image_tag("burger-colour.png", class: "img-fluid")
  end

  def display_date(post)
    post.updated_at.strftime('%-d %b %Y  %H:%M')
  end

  private

  def img_column(post)
    content_tag(:div, class: "col-sm-4") do
      image_tag(post.image, class: "rounded img-fluid")
    end
  end

  def post_column(post)
    content_tag(:div, class: "col-sm-8 mt-6") do
      [
        content_tag(:div, class: "row") do
          content_tag(:p) do
            post.text
          end
        end,
        content_tag(:div, class: "row") do
          display_rating(post)
        end
      ].join.html_safe
    end
  end
end

app/views/admin/posts/_form.html.erb
<%= bootstrap_form_for [:admin, @post] do |form| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.text_area :text %>
    <p class="hint-block">
      You can use markdown in here <strong>**bold like this**</strong> <em>*italic like this*</em>
      <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">
        https://www.markdownguide.org/basic-syntax/
      </a>
    </p>
  </p>

  <p>
    <%= form.select :rating, (0..10).to_a.map{|n| [n, n]} %>
  </p>


  <%= form.file_field :image %>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/admin/posts/index.html.erb
<div class="container">
<table class="table" />
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= link_to post.text, edit_admin_post_path(post), class: "text-secondary" %></td>
      <td>
        <%= link_to "#{post.comments.length} comments", admin_post_comments_path(post) %>
      </td>
      <td>
        <%= link_to 'X', admin_post_path(post), class: "btn btn-danger btn-xs",
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
    </td>
    </tr>
  <% end %>
</table>
</div>

<div class="container mt-4">
  <%= link_to 'New post', new_admin_post_path, class: "btn btn-primary" %>
<div>