config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/blog')
  get '/blog', to: 'posts#index', as: 'posts'

  resources :posts, only: :index do
    resources :comments, only: :create
  end

  resources :questions, only: [:index, :create] do
    resources :question_comments, only: :create
  end

  namespace :admin do
    root 'posts#index'
    resources :posts, except: :show do
      resources :comments, only: [:index, :destroy]
    end
    
    resources :questions, only: [:index, :destroy, :edit, :update] do
      resources :question_comments, only: [:index, :create, :destroy]
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_comments, dependent: :destroy
  has_one :question_answer, dependent: :destroy
  validates :body, presence: true

  def self.search(search)
    if search and search != ""
      Question.where('body like ?', "%#{search}%")
    else
      Question.all
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  def index
    @questions = Question.all
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to admin_questions_path
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  private

  def question_params
    params.require(:question).permit(:answer)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  helper_method :sort_column, :sort_direction, :search

  def index
    @question = Question.new
    @questions = questions
  end

  def question_params
    params.require(:question).permit(:search, :body, :author)
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = "Thank you. The Hog will respond to your burger related query at his lesuire."
      redirect_to action: :index
    else
      flash[:error] = "Sorry, your burger related query could not be saved at this time."
      @questions = questions
      render 'index'
    end
  end

  private

  def questions
    questions = Question.search(params[:search])
    if sort_direction != ''
      questions = questions.order("#{sort_column} #{sort_direction}")
    else
      questions = questions.order("updated_at desc")
    end
    questions
  end

  def sortable_columns
    %w[updated_at]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : 'rating'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : ''
  end

  def search
    params[:search]
  end
end

app/views/admin/questions/_form.html.erb
<%= bootstrap_form_for [:admin, @question] do |form| %>
 
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= @question.body %>
  </p>
 
  <p>
    <%= form.text_area :answer %>
    <p class="hint-block">
      You can use markdown in here <strong>**bold like this**</strong> <em>*italic like this*</em>
      <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">
        https://www.markdownguide.org/basic-syntax/
      </a>
    </p>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/admin/questions/edit.html.erb
<div class="container pb-2 mt-4 mb-2 border-bottom">
  <h1>Answer Question</h1>
</div>

<div class="container">
  <%= render 'form' %>

  <%= link_to 'Back', admin_questions_path %>
</div>

app/views/admin/questions/index.html.erb
<div class="container">
<table class="table" />
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th></th>

  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><p class="text-secondary"><%= question.body %></p></td>
      <td><p class="text-secondary"><%= question.answer %></p></td>
      <td>
        <%= link_to "#{question.question_comments.length} comments", admin_question_question_comments_path(question) %>
      </td>
      <td>
        <%= link_to 'Add/edit answer',
            edit_admin_question_path(question),
            class: 'btn btn-primary btn-xs' %>
      </td>
      <td>
        <%= link_to 'X', admin_question_path(question), class: "btn btn-danger btn-xs",
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/admin/questions/new.html.erb
<div class="container pb-2 mt-4 mb-2 border-bottom">
  <h1>New Post</h1>
</div>

<div class="container">
  <%= render 'form' %>

  <%= link_to 'Back', admin_posts_path %>
</div>